osqasource/trunk/forum_modules/exporter/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.utils.translation import ugettext as _

from views import state, running, download

urlpatterns = patterns('',
    url(r'^%s%s%s$' % (_('admin/'), _('exporter/'), _('state/')),  state, name='exporter_state'),
    url(r'^%s(?P<mode>\w+)/%s$' % (_('admin/'), _('running/')),  running, name='exporter_running'),
    url(r'^%s%s%s$' % (_('admin/'), _('exporter/'), _('download/')),  download, name='exporter_download'),
)

osqasource/trunk/forum_modules/robotstxt/urls.py
from django.conf.urls.defaults import *
from django.http import  HttpResponse
import settings

urlpatterns = patterns('',
    (r'^robots.txt$',  lambda r: HttpResponse(settings.ROBOTS_FILE.value)),
)

osqasource/trunk/forum_modules/updates/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.utils.translation import ugettext as _

from views import updater_index, updater_check

urlpatterns = patterns('',
    url(r'^%s%s%s$' % (_('admin/'), _('updater/'), _('check/')),  updater_check, name='updater_check'),
)

osqasource/trunk/urls.py
from django.conf.urls.defaults import *
from django.utils.translation import ugettext as _
from django.conf import settings

urlpatterns = patterns('',
    (r'', include('forum.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns = patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    ) + urlpatterns

handler404 = 'forum.views.meta.page'
handler500 = 'forum.views.meta.error_handler'

osqasource/trunk/forum/models/meta.py
from django.utils.translation import ugettext as _
from base import *

class Vote(models.Model):
    user = models.ForeignKey(User, related_name="votes")
    node = models.ForeignKey(Node, related_name="votes")
    value = models.SmallIntegerField()
    action = models.OneToOneField(Action, related_name="vote")
    voted_at = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        app_label = 'forum'
        unique_together = ('user', 'node')


class Flag(models.Model):
    user = models.ForeignKey(User, related_name="flags")
    node = models.ForeignKey(Node, related_name="flags")
    reason = models.CharField(max_length=300)
    action = models.OneToOneField(Action, related_name="flag")
    flagged_at = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        app_label = 'forum'
        unique_together = ('user', 'node')


class Badge(BaseModel):
    GOLD = 1
    SILVER = 2
    BRONZE = 3

    type        = models.SmallIntegerField()
    cls         = models.CharField(max_length=50, null=True)
    awarded_count = models.PositiveIntegerField(default=0)
    
    awarded_to    = models.ManyToManyField(User, through='Award', related_name='badges')

    def get_handler(self):
        from forum.badges import BadgesMeta
        return BadgesMeta.by_id.get(self.id, None)

    @property
    def name(self):
        cls = self.get_handler()
        return cls and cls.name or _("Unknown")

    @property
    def description(self):
        cls = self.get_handler()
        return cls and cls.description or _("No description available")

    @models.permalink
    def get_absolute_url(self):
        return ('badge', [], {'id': self.id, 'slug': slugify(self.name)})

    def save(self, *args, **kwargs):
        if isinstance(self.awarded_count, models.expressions.ExpressionNode):
            super(Badge, self).save(*args, **kwargs)
            self.awarded_count = self.__class__.objects.filter(id=self.id).values_list('awarded_count', flat=True)[0]
        else:
            super(Badge, self).save(*args, **kwargs)


    class Meta:
        app_label = 'forum'


class Award(models.Model):
    user = models.ForeignKey(User)
    badge = models.ForeignKey('Badge', related_name="awards")
    node = models.ForeignKey(Node, null=True)

    awarded_at = models.DateTimeField(default=datetime.datetime.now)

    trigger = models.ForeignKey(Action, related_name="awards", null=True)
    action = models.OneToOneField(Action, related_name="award")


    class Meta:
        unique_together = ('user', 'badge', 'node')
        app_label = 'forum'

osqasource/trunk/forum/models/question.py
from base import *
from tag import Tag
from django.utils.translation import ugettext as _

class QuestionManager(NodeManager):
    def search(self, keywords):
        return False, self.filter(models.Q(title__icontains=keywords) | models.Q(body__icontains=keywords))

class Question(Node):
    class Meta(Node.Meta):
        proxy = True

    answer_count = DenormalizedField("children", ~models.Q(state_string__contains="(deleted)"), node_type="answer")
    accepted_count = DenormalizedField("children", ~models.Q(state_string__contains="(deleted)"), node_type="answer", marked=True)
    favorite_count = DenormalizedField("actions", action_type="favorite", canceled=False)

    friendly_name = _("question")
    objects = QuestionManager()

    @property
    def closed(self):
        return self.nis.closed

    @property    
    def view_count(self):
        return self.extra_count

    @property
    def headline(self):
        return self._headline()

    def _headline(self):
        if self.nis.deleted:
            return _('[deleted] ') + self.title

        if self.nis.closed:
            return _('[closed] ') + self.title

        return self.title

    @property
    def accepted_answers(self):
        return self.answers.filter(~models.Q(state_string__contains="(deleted)"), marked=True)

    @models.permalink    
    def get_absolute_url(self):
        return ('question', (), {'id': self.id, 'slug': django_urlquote(slugify(self.title))})
        
    def meta_description(self):
        return self.summary

    def get_revision_url(self):
        return reverse('question_revisions', args=[self.id])

    def get_related_questions(self, count=10):
        cache_key = '%s.related_questions:%d:%d' % (settings.APP_URL, count, self.id)
        related_list = cache.get(cache_key)

        if related_list is None:
            related_list = Question.objects.filter_state(deleted=False).values('id').filter(tags__id__in=[t.id for t in self.tags.all()]
            ).exclude(id=self.id).annotate(frequency=models.Count('id')).order_by('-frequency')[:count]
            cache.set(cache_key, related_list, 60 * 60)

        return [Question.objects.get(id=r['id']) for r in related_list]
    



class QuestionSubscription(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Node)
    auto_subscription = models.BooleanField(default=True)
    last_view = models.DateTimeField(default=datetime.datetime.now())

    class Meta:
        app_label = 'forum'


class QuestionRevision(NodeRevision):
    class Meta:
        proxy = True
        

osqasource/trunk/forum/models/tag.py
import datetime
from base import *

from django.conf import settings as django_settings
from django.core.cache.backends.base import BaseCache
from django.utils.translation import ugettext as _
from django.utils.encoding import smart_unicode, force_unicode

from forum import modules

class ActiveTagManager(CachedManager):
    use_for_related_fields = True

    def get_query_set(self):
        return super(ActiveTagManager, self).get_query_set().exclude(used_count__lt=1)

class Tag(BaseModel):
    name            = models.CharField(max_length=255, unique=True)
    created_by      = models.ForeignKey(User, related_name='created_tags')
    created_at      = models.DateTimeField(default=datetime.datetime.now, blank=True, null=True)
    marked_by       = models.ManyToManyField(User, related_name="marked_tags", through="MarkedTag")
    # Denormalised data
    used_count = models.PositiveIntegerField(default=0)

    active = ActiveTagManager()

    class Meta:
        ordering = ('-used_count', 'name')
        app_label = 'forum'

    def __unicode__(self):
        return force_unicode(self.name)

    def add_to_usage_count(self, value):
        if self.used_count + value < 0:
            self.used_count = 0
        else:
            self.used_count = models.F('used_count') + value

    def cache_key(self):
        return self._generate_cache_key(Tag.safe_cache_name(self.name))

    @classmethod
    def safe_cache_name(cls, name):
        return "".join([str(ord(c)) for c in name])

    @classmethod
    def infer_cache_key(cls, querydict):
        if 'name' in querydict:
            cache_key = cls._generate_cache_key(cls.safe_cache_name(querydict['name']))

            if len(cache_key) > django_settings.CACHE_MAX_KEY_LENGTH:
                cache_key = cache_key[:django_settings.CACHE_MAX_KEY_LENGTH]

            return cache_key

        return None

    @classmethod
    def value_to_list_on_cache_query(cls):
        return 'name'

    @models.permalink
    def get_absolute_url(self):
        return ('tag_questions', (), {'tag': self.name})

class MarkedTag(models.Model):
    TAG_MARK_REASONS = (('good', _('interesting')), ('bad', _('ignored')))
    tag = models.ForeignKey(Tag, related_name='user_selections')
    user = models.ForeignKey(User, related_name='tag_selections')
    reason = models.CharField(max_length=16, choices=TAG_MARK_REASONS)

    class Meta:
        app_label = 'forum'

osqasource/trunk/forum/forms/admin.py
import socket
from django import forms
from django.utils.translation import ugettext as _
from django.contrib.admin.widgets import FilteredSelectMultiple, AdminDateWidget
from qanda import TitleField, EditorField
from forum import settings
from forum.models.node import NodeMetaClass
from forum.models import User

class IPListField(forms.CharField):
    def clean(self, value):
        ips = [ip.strip() for ip in value.strip().strip(',').split(',')]
        iplist = []

        if len(ips) < 1:
            raise forms.ValidationError(_('Please input at least one ip address'))

        for ip in ips:
            try:
                socket.inet_aton(ip)
            except socket.error:
                raise forms.ValidationError(_('Invalid ip address: %s' % ip))

            if not len(ip.split('.')) == 4:
                raise forms.ValidationError(_('Please use the dotted quad notation for the ip addresses'))

            iplist.append(ip)

        return iplist

class MaintenanceModeForm(forms.Form):
    ips = IPListField(label=_('Allow ips'),
                      help_text=_('Comma separated list of ips allowed to access the site while in maintenance'),
                      required=True,
                      widget=forms.TextInput(attrs={'class': 'longstring'}))

    message = forms.CharField(label=_('Message'),
                              help_text=_('A message to display to your site visitors while in maintainance mode'),
                              widget=forms.Textarea)


TEMPLATE_CHOICES = (
('default', _('Default')),
('sidebar', _('Default with sidebar')),
('none', _('None')),
)

RENDER_CHOICES = (
('markdown', _('Markdown')),
('html', _('HTML')),
('escape', _('Escaped'))
)

class UrlFieldWidget(forms.TextInput):
    def render(self, name, value, attrs=None):
        if not value:
            value = ''

        return """
                <input class="url_field" type="text" name="%(name)s" value="%(value)s" />
                <a class="url_field_anchor" target="_blank" href="%(app_url)s"></a>
            """  % {'name': name, 'value': value, 'app_url': settings.APP_URL}


class PageForm(forms.Form):
    def __init__(self, page, *args, **kwargs):
        if page:
            initial = page.extra
            initial.update(dict(title=page.title, content=page.body))
            super(PageForm, self).__init__(initial=initial, *args, **kwargs)
        else:
            super(PageForm, self).__init__(*args, **kwargs)


    title  = forms.CharField(label=_('Title'), max_length=255, widget=forms.TextInput(attrs={'class': 'longstring'}),
                             initial='New page')
    path  = forms.CharField(label=_('Page URL'), widget=UrlFieldWidget, initial='pages/new/')

    content = forms.CharField(label=_('Page Content'), widget=forms.Textarea(attrs={'rows': 30}))
    mimetype = forms.CharField(label=_('Mime Type'), initial='text/html')

    render = forms.ChoiceField(widget=forms.RadioSelect, choices=RENDER_CHOICES, initial='markdown',
                               label=_('Render Mode'))

    template = forms.ChoiceField(widget=forms.RadioSelect, choices=TEMPLATE_CHOICES, initial='default',
                                 label=_('Template'))
    sidebar = forms.CharField(label=_('Sidebar Content'), widget=forms.Textarea(attrs={'rows': 20}), required=False)
    sidebar_wrap = forms.BooleanField(label=_("Wrap sidebar block"), initial=True, required=False)
    sidebar_render = forms.ChoiceField(widget=forms.RadioSelect, choices=RENDER_CHOICES, initial='markdown',
                                       label=_('Sidebar Render Mode'))

    comments = forms.BooleanField(label=_("Allow comments"), initial=False, required=False)

from forum.forms.auth import SimpleRegistrationForm
from forum.forms.general import SetPasswordForm


class CreateUserForm(SimpleRegistrationForm, SetPasswordForm):
    validate_email = forms.BooleanField(required=False, label=_('send validation email'))

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['username', 'email', 'validate_email', 'password1', 'password2']
        self.fields['email'].label = _('email address')


    

osqasource/trunk/forum/skins/default/templates/401.html
{% extends "base_content.html" %}
{% load i18n %}
{% block title %}{% trans "Not logged in" %}{% endblock %}
{% block meta %}
    <!-- <meta http-equiv="refresh" content="5;url={% url auth_signin %}"> -->
{% endblock %}
{% block forestyle%}
    <style type="text/css">
 		form input { margin-right: 5px; }
	</style>
{% endblock %}
{% block forejs %}
       <script type="text/javascript">
        $().ready(function(){
            window.setInterval(function() {
                $('#redirect_loader').html($('#redirect_loader').html() + '.')
            }, 800);

            window.setTimeout(function() {
                window.location = "{% url auth_signin %}";
            }, 5000);
        });

        </script>
{% endblock %}
{% block content %}
<div id="main-bar" class="headNormal">
    {% trans "Not logged in" %}
</div>
<div id="main-body" class="">
    <div style="padding:5px 0px 10px 0;line-height:25px;">
        <h3>{% trans "You are not logged in..." %}</h3>
        <div style="margin-top:5px">
            {% trans "...and the resource you're trying to access is protected." %}
            <p>
                {% trans "Redirecting to the login page." %}<span id="redirect_loader"></span>
            </p>
            <p>
                {% trans "If you're not automatically redirected in 5 seconds, please click" %}
                <a href="{% url auth_signin %}">{% trans "here" %}</a>.
            </p>
        </div>
    </div>

</div>
{% endblock %}

osqasource/trunk/forum/skins/default/templates/badges.html
{% extends "base.html" %}
<!-- template badges.html -->
{% load extra_tags %}
{% load humanize %}
{% load i18n %}
{% block title %}{% spaceless %}{% trans "Badges summary" %}{% endspaceless %}{% endblock %}
{% block content %}
<div class="headlineA">
        <span class="headMedals">{% trans "Badges" %}</span>
</div>
<div class="badges" id="main-body" style="width:100%">
    <p>
	{% trans "Community gives you awards for your questions, answers and votes." %}
	{% blocktrans %}Below is the list of available badges and number of times each type of badge has been awarded.
    {% endblocktrans %}
    </p>
    <div id="medalList">
        {% for badge in badges %}
        <div style="clear:both;line-height:30px">
            <div class="intoMyBadges">
            {% if badge.id in mybadges %}
                 <span>&#10004;</span>
            {% endif %}
            </div>
            <div class="badgeListItem">
                <a href="{{badge.get_absolute_url}}" title="{{ badge.get_type_display }} : {{ badge.description }}" class="medal"><span class="badge{{ badge.type }}">&#9679;</span>&nbsp;{{ badge.name }}</a><strong> &#215; {{ badge.awarded_count|intcomma }}</strong>
            </div>
            <p class="badgeListDescription">
                {{ badge.description }}
            </p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
{% block sidebar %}

<div class="boxC">
    <h3>{% trans "Community badges" %}</h3>
    <div class="body">
    <p>
        <span title="{% trans "gold badge: the highest honor and is very rare" %}" class="medal"><span class="badge1">&#9679;</span>&nbsp;{% trans "gold" %}</span>
    </p>
    <p>
	{% trans "gold badge description" %}
    </p>
    <p>
        <span
			title="{% trans "silver badge: occasionally awarded for the very high quality contributions" %}" 
			class="medal"><span class="badge2">&#9679;</span>&nbsp;{% trans "silver" %}</span>
    </p>
    <p>
	{% trans "silver badge description" %}
    </p>
    <p>
        <span title="{% trans "bronze badge: often given as a special honor" %}" class="medal">
		<span class="badge3">&#9679;</span>&nbsp;{% trans "bronze" %}</span>
    </p>
    <p>
	{% trans "bronze badge description" %}
    </p>
    </div>
</div>
{% endblock %}
<!-- end template badges.html -->

osqasource/trunk/forum/skins/default/templates/base.html
{% extends "base_content.html" %}
{% block page_center %}

{% block full_width_banner %}{% endblock %}

<div id="wrapper">
    {% block site_width_banner %}{% endblock %}
    
    <div id="room">
        <div id="CALeft">
            {% block content%}
            {% endblock%}

        </div>
        <div id="CARight">
            {% block sidebar%}
            {% endblock%}

        </div>
        <div id="tail" style="clear:both;">
            {% block tail %}
            {% endblock %}
        </div>
    </div>
    <div class="spacer3"></div>
</div>
{% endblock %}

osqasource/trunk/forum/skins/default/templates/close.html
{% extends "base_content.html" %}
<!-- template close.html -->
{% load i18n %}
{% load extra_tags %}
{% load humanize %}
{% block title %}{% spaceless %}{% trans "Close question" %}{% endspaceless %}{% endblock %}
{% block forejs %}
       <script type="text/javascript">
        $().ready(function(){
            $('#btBack').bind('click', function(){ history.back(); });
        });
        </script>
{% endblock %}
{% block content %}
<div id="main-bar" class="headNormal">
	{% trans "Close question" %}
</div>
<div id="main-body" style="width:100%;margin-bottom:10px">
    <p>{% trans "Close the question" %}: <a href="{{ question.get_absolute_url }}">
    <strong>{{ question.get_question_title }}</strong></a>
    </p>   
    
    <form id="fmclose" action="{% url close question.id %}" method="post" >
        {% csrf_token %}
        <p>
            <strong>{% trans "Reasons" %}:</strong> {{ form.reason }}
        </p>
        <div id="" style="padding-top:20px">
            <input type="submit" value="{% trans "OK to close" %}" class="submit" />
            <input id="btBack" type="button" class="submit" value="{% trans "Cancel" %}"  />
            
        </div>
        
    </form>
</div>
{% endblock %}
<!-- end template close.html -->

osqasource/trunk/forum/skins/default/templates/email_base.html
{% load extra_filters %}
{% load extra_tags %}
{% load email_tags %}
{% load i18n %}

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <style type="text/css">
            body {
                background: #FFF;
                font-size: 12px;
                line-height: 150%;
                margin: 0;
                padding: 0;
                color: #000;
                font-family: sans-serif;
            }

            #wrapper {
                width: 600px;
                margin: auto;
                padding: 0;
            }

            a img {
                border: none;
            }
        </style>
    </head>
    <body>
        <a href="{% fullurl index %}">
            <img src="cid:logo" title="{% trans "home" %}" alt="{{settings.APP_TITLE}} logo"/>
        </a>
        <br />
        <p>{{ settings.APP_TITLE }}</p>
    <br /><br />
    <div id="wrapper">
            <div id="room">
                <div id="CALeft">
                    {% block content%}
                    {% endblock%}
                </div>
            </div>
            <div class="spacer3"></div>
        </div>
    </body>
</html>

osqasource/trunk/forum/skins/default/templates/feedback.html
{% extends "base_content.html" %}
<!-- template about.html -->
{% load i18n %}
{% load extra_tags %}
{% load humanize %}
{% block title %}{% spaceless %}{% trans "Feedback" %}{% endspaceless %}{% endblock %}
{% block forejs %}
{% endblock %}
{% block content %}
<div class="headNormal">
{% trans "Give us your feedback!" %}
</div>
<div class="content">
    <form method="post" action="{% url feedback %}" accept-charset="utf-8">
        {% csrf_token %}
        {% if user.is_authenticated %}
            <p class="message">
            {% blocktrans with user.username as user_name %}
            <span class='big strong'>Dear {{user_name}}</span>, we look forward to hearing your feedback. 
            Please type and send us your message below.
            {% endblocktrans %}
            <p>
        {% else %}
            <p class="message">
            {% blocktrans %}
            <span class='big strong'>Dear visitor</span>, we look forward to hearing your feedback.
            Please type and send us your message below.
            {% endblocktrans %}
            </p>
            <div class="form-row"><label for="id_name">{{form.name.label}}</label><br/>{{form.name}}</div>
            <div class="form-row">
                <label for="id_email">{{form.email.label}}
                    {% if form.errors.email %}
                        <strong>(please enter a valid email)</strong>
                    {% endif %}
                </label><br/>{{form.email}}
            </div>
        {% endif %}
        <div class="form-row">
            <label for="id_message">{{form.message.label}}
            {% if form.errors.message %}
            <strong>{% trans "(this field is required)" %}</strong>
            {% endif %}
            </label>
            <br/>
            {{form.message}}
        </div>

        {% if form.recaptcha %}
        <div class="form-row">
            <label for="recaptcha_response_field">Are you a human?
            {% if form.errors.recaptcha %}
            <strong>{% trans "(wrong captcha)" %}</strong>
            {% endif %}
            </label>
            <br/>
            <div style="float: left;">
            {{ form.recaptcha }}
            </div>
            <div class="clear"></div>
        </div>
        {% endif %}

        {{form.next}}
        <div class="submit-row">
            <input type="submit" class="submit" value="{% trans "Send Feedback" %}"/>
            <input type="submit" class="submit" name="cancel" value="{% trans "Cancel" %}"/>
        </div>
    </form>
</div>
{% endblock %}
<!-- end template about.html -->

osqasource/trunk/forum/skins/default/templates/index.html
{% extends "questions.html" %}
<!-- index.html -->
{% load general_sidebar_tags %}
{% load question_list_tags %}
{% load i18n %}
{% block fulltitle %}{{ settings.APP_TITLE }}{% endblock %}
{% block sidebar %}
    {% if not request.user.is_authenticated %}
        {% if settings.SHOW_WELCOME_BOX %}
            <div class="boxA">
                <h3>{% trans "welcome to " %}{{ settings.APP_SHORT_NAME }}</h3>
                <div class="body">
                  {{ settings.APP_INTRO|safe }}
                  <div class="more"><a href="{% url about %}">{% trans "about" %} </a></div>
                  <div class="more"><a href="{% url faq %}">{% trans "faq" %} </a></div>
                </div>
            </div>
        {% endif %}
    {% endif %}
    {% include "question_list/count.html" %}
    {% sidebar_upper %}
    {% if request.user.is_authenticated %}
        {% tag_selector %}
    {% endif %}
    {% sidebar_lower %}
    {% recent_tags %}
    {% recent_awards %}
{% endblock %}
<!-- index.html -->


osqasource/trunk/forum/skins/default/templates/page.html
{% extends base %}
{% load i18n markup node_tags general_sidebar_tags %}
{% block title %}{% spaceless %}{{ page.title }}{% endspaceless %}{% endblock %}

{% block content %}
<div class="headNormal">{{ page.title }}</div>
<div class="content">
{{ body }}
</div>
{% if page.extra.comments %}
    {% comments page request.user %}
{% endif %}
{% endblock %}

{% ifequal page.extra.template "sidebar" %}
    {% block sidebar %}
        {% sidebar_upper %}
        {% if page.extra.sidebar %}
            {% if page.extra.sidebar_wrap %}<div class="boxC"><div class="body">{% endif %}
                {{ sidebar }}
            {% if page.extra.sidebar_wrap %}</div></div>{% endif %}
        {% endif %}
        {% sidebar_lower %}
    {% endblock %}
{% endifequal %}

osqasource/trunk/forum/skins/default/templates/question_retag.html
{% extends "base.html" %}
<!-- question_retag.html -->
{% load extra_tags %}
{% load i18n %}
{% block title %}{% spaceless %}{% trans "Change tags" %}{% endspaceless %}{% endblock %}
{% block forejs %}
        <script type="text/javascript">
        
        $().ready(function(){
            $("#id_tags").autocomplete("{% url matching_tags %}", {
        		matchContains: true,
                max: 20,
                multiple: true,
                multipleSeparator: " ",
                highlightItem: true,
                scroll: true,
                scrollHeight: 300,
        		/*formatItem: function(row, i, max) {
        			return row.n + " ("+ row.c +")";
        		},
                formatResult: function(row, i, max){
                    return row.n;
                }*/
                formatItem: function(row, i, max, value) {
                    return row[1] + " (" + row[2] + ")";
                },

                formatResult: function(row, i, max, value){
                    return row[1];
                }
                
            });

        });
        </script>
{% endblock %}
        
{% block content %}
<div id="main-bar" class="headNormal">
    {% trans "Change tags" %} [<a href="{{ question.get_absolute_url }}">{% trans "back" %}</a>]
</div>
<div id="main-body" class="ask-body">
    <div id="askform">
        <form id="fmretag" action="{% url edit_question question.id %}" method="post">
            {% csrf_token %}
            <h3>
                {{ question.headline }}
            </h3>
            <div id="description" class="edit-content-html">
                {{ question.html|safe }}
            </div>
           
            
            <div class="form-item">
                <strong>{{ form.tags.label_tag }}:</strong> <span class="form-error"></span><br/>
                {{ form.tags }}  {{ form.tags.errors }}
                <div class="title-desc">
                    {{ form.tags.help_text }}
                </div>
            </div>
            <div class="error" ></div>
            <input type="submit" value="{% trans "Save edit" %}" class="submit" />
            <input type="button" value="{% trans "Cancel" %}" class="submit" onclick="history.back(-1);" />
        </form>
    </div>
</div>
{% endblock %}

{% block sidebar %}
<div class="boxC">
    <p class="subtitle">{% trans "Why use and modify tags?" %}</p>
    <ul class="list-item">
        <li>
            {% trans "tags help us keep Questions organized" %}
        </li>
        <li>
            {% trans "tag editors receive special awards from the community" %}
        </li>
    </ul>
    <p class='info-box-follow-up-links'>
        <a href="{% url faq %}">faq &raquo;</a>
    </p>
</div>

{% endblock %}

{% block endjs %}
{% endblock %}
<!-- end question_retag.html -->

osqasource/trunk/forum/skins/default/templates/questions.html
{% extends "base.html" %}
<!-- questions.html -->
{% load question_list_tags %}
{% load i18n %}
{% load extra_tags %}
{% load general_sidebar_tags %}

{% block title %}{% spaceless %}{{ page_title }}{% endspaceless %}{% endblock %}

{% block metadescription %}{% spaceless %}
    {% if tag %}
        {% blocktrans with settings.APP_TITLE as app_title %}Questions and answers about {{ tag }} on {{ app_title }}{% endblocktrans %}
    {% endif %}
{% endspaceless %}{% endblock %}

{% block meta %}
    <link rel="alternate" type="application/rss+xml" title="RSS" href="{{ feed_url }}" />
{% endblock %}

{% block content %}

<div class="tabBar">
    {% include "question_list/title.html" %}
    <a class="feed-icon" style="background-image:url('{% media "media/images/feed-icon-small.png" %}');" href="{{ feed_url }}" title="{% trans "subscribe to question RSS feed" %}"></a>
    {{ questions.paginator.sort_tabs }}
</div>
<div id="listA">{% for question in questions.paginator.page %}
    {% question_list_item question %}
{% endfor %}</div>
{% endblock %}

{% block tail %}
    <div class="pager">{{ questions.paginator.page_numbers }}</div>
    <div class="pagesize">{{ questions.paginator.page_sizes }}</div>
{% endblock %}

{% block sidebar %}
    {% include "question_list/count.html" %}
    {% sidebar_upper %}
    {% tag_selector %}
    {% sidebar_lower %}
    {% question_list_related_tags questions.paginator.page %}

{% endblock %}
<!-- end questions.html -->

osqasource/trunk/forum/skins/default/templates/search.html
{% extends "base_content.html" %}

{% load i18n %}

{% block content %}
<div id="main-bar" class="headNormal">
	{% blocktrans with settings.APP_SHORT_NAME as app_name %}
	    Search in {{  app_name }}
	{%  endblocktrans %}
</div>
<div id="main-body" style="text-align: center; height: 400px;">
<form action="{% url search %}" method="get">
    {% csrf_token %}
    <div>
        <input type="text" class="searchInput" value="{{ keywords }}" name="q" id="keywords" style="width: 600px" />
        <input type="submit" name="Submit" value="{% trans "search" %}" class="searchBtn" />
    </div>
    <div class="options">
        <input id="type-question" type="radio" value="question" name="t"
            checked="checked" /><label for="type-question">{% trans "questions" %}</label>
        <input id="type-tag" type="radio" value="tag" name="t" /><label for="type-tag">{% trans "tags" %}</label>
        <input id="type-user" type="radio" value="user" name="t" /><label for="type-user">{% trans "users" %}</label>
    </div>
</form>
</div>
{% endblock %}